### ISSUE TITLE
Как правильно описать параметр URL?

### ISSUE THREAD

**Issue by PeresadaMY** [zerobig/swagger-1c#15]
Добрый день!
Не нашел подобного примера в тестовом расширении.
Как я могу описать параметр URL?

У меня есть метод Api
/partner-portal-api/user/{ПользовательAD}/task/list
Я описываю [path ](https://alor.dev/docs/api/usage/syntax-http/#path-params) параметр следующим образом:
``` bsl
Функция ПользовательЗадачиСписокGETПараметры() Экспорт
	
	ПользовательЗадачиСписокGETПараметры = Новый Массив;
	ПользовательЗадачиСписокGETПараметры.Добавить(Swag_ФормированиеОписаний.ОписаниеПараметра("ПользовательAD", "AD идентификатор пользователя", "path", Истина));
		
	Возврат ПользовательЗадачиСписокGETПараметры; 
	
КонецФункции
```

При попытке затестировать данный запрос в swagger (Кнопка Try it out) указанный параметр не подставляется в URL.
Вариант представления ключа "ПользовательAD" в "{ПользовательAD}" также не даёт своих результатов.

Скриншот проблемы ниже:
https://iimg.su/i/v4DLp

**Comment by zerobig** [comment]
Вы абсолютно правильно описываете параметр. Скорее всего проблема связана вот с этим #12 
Я внёс исправления в кодовую базу, но релиз ещё не выкатывал.
Сами соберёте исправленную версию? Или мне оперативно выпустить обновление?

**Comment by PeresadaMY** [comment]
@zerobig спасибо, будет здорово, если выпустите патч с исправлением

**Comment by zerobig** [comment]
@PeresadaMY https://github.com/zerobig/swagger-1c/releases/tag/1.2.3
