### ISSUE TITLE
Идеи по развитию

### ISSUE THREAD

**Issue by PeresadaMY** [zerobig/swagger-1c#16]
### Скрытие сервисов из расширений
Было бы удобно, при снятии активности у расширения, сервисы из расширения не отображались в swagger'e.
Или иметь возможность настройки отображаемых сервисов, так как сейчас понимаю, парсятся все сервисы конфигурации.

### Добавление описания
Над полем с параметрами на странице swagger'а было бы удобно иметь поле в которое можно поместить дополнительную информацию, такую как ссылка на confluence или краткие особенности этого метода.

**Comment by zerobig** [comment]
> Скрытие сервисов из расширений
Было бы удобно, при снятии активности у расширения, сервисы из расширения не отображались в swagger'e.
Или иметь возможность настройки отображаемых сервисов, так как сейчас понимаю, парсятся все сервисы конфигурации.

Идея здравая. Надо только определиться с местом хранения этой информации. Настройка через код? Регистр сведений с метаданными? Или какое-то ещё место?

Пока мне видится как-то так. В общем модуле описания ещё одна экспортная функцияс настройками HTTP-сервиса:
```bsl
Функция ОбщиеНастройки() Экспорт

	Возврат Новый Структура("НеОтображать", Истина);

КонецФункции
```

> Добавление описания
Над полем с параметрами на странице swagger'а было бы удобно иметь поле в которое можно поместить дополнительную информацию, такую как ссылка на confluence или краткие особенности этого метода.

@PeresadaMY Можно скриншот? По текстовому описанию не до конца понял место расположения. Есть description у тега (tags). Этого будет достаточно? Чем заполнять? Комментарием из HTTP-сервиса или каким-то способом из кода (опять же, к примеру, из функции ```ОбщиеНастройки```)?

**Comment by zerobig** [comment]
Предварительно как-то так: da6353cab6b5f80bd92e23e7f083a2547e65cdcc

Не выводить описание:

```bsl
Функция ОбщиеНастройки() Экспорт

	Возврат Новый Структура("НеОтображать", Истина);

КонецФункции
```

Описание из кода:

```bsl
Функция ОбщиеНастройки() Экспорт

	Возврат Новый Структура("Описание", "Пример описания из кода. Пример гиперссылки в описании: <a href=""http://example.com"">example.com</a>");

КонецФункции
```

Если в функции ```ОбщиеНастройки``` описание не задано, то берётся из комментария HTTP-сервиса

@PeresadaMY Нормально? Релиз нужен оперативно? Или самостоятельно пока соберёте?

**Comment by zerobig** [comment]
![#16](https://github.com/user-attachments/assets/fc44b45b-91da-4f32-840e-75cb41799c1c)

**Comment by PeresadaMY** [comment]
### Отображение
По поводу отображения, я бы пошел от обратного.
На аналогии с тем, как подлючается какой-то функционал в БСП, в самом сервисе надо было описывать процедуру описания или в общем модуле с описанием методов.
``` bsl
Функция ОписаниеСервиса() Экспорт
	Возврат Swag_ОписаниеСервиса("Комментарий"); // Пока только комментарий, но в общем можно будет и дальше разворачивать
КонецФункции
```

А также общий модуль **ПодключаемыеСервисыПереопределяемый** в котором описывались все подключенные сервисы
``` bsl
Функция ОпределитьСервисы() Экспорт
	
	ПодключаемыеСервисвы = Новый Массив;
	ПодключаемыеСервисвы.Добавить("ТестовыйHTTP1"); // Аналогично, пока только имя сервисов, в будущем может понадобиться что-то более масштабное
	ПодключаемыеСервисвы.Добавить("ТестовыйHTTP2");
	ПодключаемыеСервисвы.Добавить("ТестовыйHTTP3");
	
	Возврат ПодключаемыеСервисвы;
	
КонецФункции
```

### Описание методов
При описании метода представить параметр ОписаниеМетода в виде структуры, где можно заполнять Краткое описание и Расширенное

``` bsl
Функция ПолучитьОписаниеHTTPСервиса() Экспорт
	
	Объекты = ПолучитьОбъектыHTTPСервиса();
	
	ТестGET_MIME_Success = Новый Массив;
	ТестGET_MIME_Success.Добавить(ОписаниеТипаMIME("application/json", "array", Объекты[0].Имя));
	
	ТестGETОтветы = Новый Массив;
	ТестGETОтветы.Добавить(ОписаниеОтвета(200, "Success", ТестGETОтветы));
	
	Аннотация = Новый Структура("Описание", "Информация");
	Аннотация.Описание = "Это тестовое описание метода";
	Аннотация.Информация =
		"Важно учитывать, что оценка не будет создана если по задаче подрядчика уже есть оценки на согласовании или редактировании.
		|Подробное описание данного метода можно посмотреть тут <a href=""http://example.com"">example.com</a>";
	
	Описание = Новый Массив;
	Описание.Добавить(ОписаниеМетода(
		"ТестGET",
		Аннотация,
		ТестGETПараметры(),
		ТестGETОтветы)
	);
	
	Возврат Описание;
	
	
КонецФункции

```
![image](https://github.com/user-attachments/assets/1761a2d6-0aa8-413f-b58c-af0e60c130ef)

**Comment by zerobig** [comment]
> ПодключаемыеСервисыПереопределяемый 

Мне резко не нравится такой подход. 1С конечно не про ООП, но этот подход нарушает принципы SOLID:

- Single Responsibility - одно дело когда все параметры для формирования описания хранятся в соответствующих модулях (одно описание равно одному HTTP-сервису), а совсем другое когда код начинает расползаться: описание в одном модуле, а видимость в переопределяемом.

Я понимаю что таким образом 1С пытается компенсировать отсутствие ООП и сохранить при этом управляемость кодовой базы, но это не отменяет "костыльность" такого подхода.

> Описание методов

Теперь понял. Почему-то подумал что вопрос про описание самого HTTP-сервиса.

Сделаю.

Наверное описание HTTP-сервиса, которое я уже добавил в код, убирать не буду.

**Comment by PeresadaMY** [comment]
> SOLID

Да согласен, что касается 1С это один большой костыль)

> Пока мне видится как-то так. В общем модуле описания ещё одна экспортная функцияс настройками HTTP-сервиса

Думаю что можно это реализовать следующий образом:
![image](https://github.com/user-attachments/assets/e7319e1b-6d15-4122-a1fd-c8f62a8ccecd)

Наличие модуля описания, говорит о том, что данный сервис необходимо показывать в сваггер, однако видимость можно определить функцией ОбщиеНастройки. Это будет полезным, когда ведутся какие-то крупные доработки или создали аналог сервиса, а прошлый используется как пример.

``` bsl
Функция ОбщиеНастройки() Экспорт

	Возврат Новый Структура("НеОтображать", Истина); 

КонецФункции
```

**Comment by zerobig** [comment]
@PeresadaMY Т.е. вы предлагаете по-умолчанию ничего не показывать?

На мой взгляд, очень плохая идея. Программист, установив расширение, не увидит ни одного HTTP-сервиса. Если бы такое произошло со мной, то я бы решил что расширение глючное и отказался бы от него. Дополнительно изучать документацию чтобы запустить разработку в базовом виде - признак плохого проектирования.

**Comment by PeresadaMY** [comment]
@zerobig Тогда думаю можно оставить 1 вариант, когда по умолчанию -показывать.

Я просто представляю ситуацию, когда у меня есть 5+ http сервисов 4 из которых поддерживаются внешним подрядчиком, а описывать я планирую только 1. По итогу для других 4 мне надо создавать общие модули описания, где указывать, что эти объекты показывать не надо.

**Comment by zerobig** [comment]
@PeresadaMY Сценарий я понял. Подумаю ещё. Пока сделал релиз с тем что есть [1.2.4](https://github.com/zerobig/swagger-1c/releases/tag/1.2.4)

**Comment by Kyrales** [comment]
> @PeresadaMY Сценарий я понял. Подумаю ещё. Пока сделал релиз с тем что есть [1.2.4](https://github.com/zerobig/swagger-1c/releases/tag/1.2.4)
@zerobig 
Подскажи, сейчас в итоге как быть с описанием? У меня не работает на 1.2.5 отображение его. В целом удобно так отражать.
![image](https://github.com/user-attachments/assets/95caeed4-a8cf-4bc3-88b1-0593d6f217f1)

**Comment by zerobig** [comment]
>Подскажи, сейчас в итоге как быть с описанием? У меня не работает на 1.2.5 отображение его. В целом удобно так отражать.

@Kyrales экспортная функция называется ```ПолучитьОбщиеНастройки```, а не ```ОбщиеНастройки```

**Comment by zerobig** [comment]
@PeresadaMY Отключение отображения HTTP-сервисов через единую точку 51b1e775b12c3872e33dce1d4bb7bd21e7ec1c45

**Comment by Kyrales** [comment]
> >Подскажи, сейчас в итоге как быть с описанием? У меня не работает на 1.2.5 отображение его. В целом удобно так отражать.
> 
> @Kyrales экспортная функция называется ```ПолучитьОбщиеНастройки```, а не ```ОбщиеНастройки```

Да привык, что слово получить уже сто лет не используется в функциях. Убрать бы это слово)

**Comment by zerobig** [comment]
>Да привык, что слово получить уже сто лет не используется в функциях. Убрать бы это слово)

@Kyrales если будут серьёзные изменения и случится смена версии на 2.0, то под шумок можно будет провести рефакторинг этого момента. А пока единообразие (все остальные экспортные функции со словом "Получить") и преемственность версий важнее.
