### ISSUE TITLE
Обязательный, минимальный, максимальный в теле запроса 

### ISSUE THREAD

**Issue by Kyrales** [zerobig/swagger-1c#17]
Крайне необходимы: Обязательный, минимальный, максимальный в теле запроса при описании обьекта. Это не параметр входной, а именно тело. 

Буду делать своими силами так как срочно нужен

**Comment by zerobig** [comment]
День добрый.

@Kyrales я правильно понял что нужно что-то такое:

```json
"components": {
  "schemas": {
    "ModelExample": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "minimum": 100,
          "maximum": 600
        }
      }
    }
  }
}
```

?

**Comment by Kyrales** [comment]
Вот пример из документации по АПИ:
![image](https://github.com/user-attachments/assets/fba4b1db-29a6-4b75-8f69-ef21daa2076a)

**Comment by Kyrales** [comment]
![image](https://github.com/user-attachments/assets/a8b8b4c7-7ede-47e7-8f38-0b1228598dc9)

**Comment by Kyrales** [comment]
Необходимо вот тут эти вставки делать:
![image](https://github.com/user-attachments/assets/d261bcb9-fe83-4ebb-88d7-3df62335ea1b)

**Comment by zerobig** [comment]
@Kyrales [1.2.5](https://github.com/zerobig/swagger-1c/releases/tag/1.2.5) все пожелания учёл? Закрываю issue?

**Comment by zerobig** [comment]
@Kyrales И да! Забыл сказать. Использовать так:
```json
{
  "exclusiveMinimum": 0
}
```
судя по спецификации неправильно. Правильно вот так:
```json
{
  "exclusiveMinimum": true
}
```

**Comment by Kyrales** [comment]
Нет, именно число для exclusiveMinimum должно быть

![Screenshot_2024-11-30-14-32-25-282_org.telegram.messenger.jpg](https://github.com/user-attachments/assets/7934c555-63b3-45a0-aafd-9cb270c8788f)

**Comment by Kyrales** [comment]
Пример добавил выше.

Параметр "exclusiveMinimum" в OpenAPI означает, что значение должно быть строго больше указанного минимального значения. Это полезно при определении ограничений для числовых значений, например, чтобы указать, что число должно быть больше определенного порога.

**Comment by zerobig** [comment]
@Kyrales Я опирался вот на это: [OpenAPI 3.0.X JSON Schema](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.yaml) строка 214
```yaml
  ...
  maximum:
    type: number
  exclusiveMaximum:
    type: boolean
    default: false
  minimum:
    type: number
  exclusiveMinimum:
    type: boolean
    default: false
  ...
```

**Comment by Kyrales** [comment]
Хорошо. Странно, проверю работу. Спасибо!
