### ISSUE TITLE
Ошибки в ЖР в случае если не все модуля описаний для API созданы 

### ISSUE THREAD

**Issue by Kyrales** [zerobig/swagger-1c#18]
Не должно быть исключений если модуля описания не создано. Недопустимое поведение системы.
![image](https://github.com/user-attachments/assets/4979da27-88db-4ea9-beba-5e2ec23b96c3)

**Comment by Kyrales** [comment]
+  опечатки в функциях : МодульОписанияHTTPСервиса.ПолучитьОбщ**еие**Настройки()

**Comment by Kyrales** [comment]
![image](https://github.com/user-attachments/assets/b0cfb1f6-300f-4de2-a43b-4ab2077d296a)


Исправленный вариант кода. Плюс логичное отсечение всякого мусорного типового api без описания. Дискуссию видел, что один коллега категорически против этого, его аргументация возможно в одном лице только.

**Comment by zerobig** [comment]
@Kyrales убрал вывод ошибок о ненайденных описаниях HTTP-сервисов в журнол регистрации 51b1e775b12c3872e33dce1d4bb7bd21e7ec1c45

**Comment by Kyrales** [comment]
А с отсечением мусорных апи получилось?

**Comment by zerobig** [comment]
Ищется общий модуль ```SwaggerОбщиеНастройки```. В нём:

```bsl
Функция ПолучитьОбщиеНастройки() Экспорт
	
	МассивНеотображаемыхСервисов= Новый Массив;
	МассивНеотображаемыхСервисов.Добавить("Exchange");
	МассивНеотображаемыхСервисов.Добавить("ПередачаДанных");
	МассивНеотображаемыхСервисов.Добавить("ЭДО");
	
	Возврат Новый Структура("МассивНеотображаемыхСервисов", МассивНеотображаемыхСервисов);
	
КонецФункции
```

Если не находится общий модуль или нет такой функции или функция вернула что-то не понятное, то отображается всё.
