### ISSUE TITLE
.Минимум(0).НеВключаяМинимум() не отрабатывает с типом number

### ISSUE THREAD

**Issue by Kyrales** [zerobig/swagger-1c#20]
Не могу понять почему схема не собирается с типом number при указании .Минимум(0).НеВключаяМинимум() . Аналогичное с integer отрабатывает.
См. скрин:
![image](https://github.com/user-attachments/assets/7d65eb3f-6152-4b54-826d-e4daabc4cf29)

**Comment by zerobig** [comment]
Прошу прощения! Упустил тип "number".
[Swagger_1.2.5.cfe.zip](https://github.com/user-attachments/files/17965683/Swagger_1.2.5.cfe.zip)
Собрал версию с исправлением для вас.

**Comment by Kyrales** [comment]
Спасибо!

**Comment by Kyrales** [comment]
Все протестировал. С number теперь все работает.
