### ISSUE TITLE
Как отразить еще только планируемый метод?

### ISSUE THREAD

**Issue by Kyrales** [zerobig/swagger-1c#21]
Правильно понимаю, что невозможно запланировать заранее метод? Мы можем описать только уже реализованные?
Очень не хватает возможности заранее планировать метод, который собирает аналитик перед перед передачей в разработку. 
Как выглядит процесс:
Сначала планируем метод, согласовываем и далее реализуем.

**Comment by zerobig** [comment]
А что мешает аналитику создать метаданные под планируемые методы? Кодом не наполнять. И создать описания на эти пустышки.

**Comment by Kyrales** [comment]
> А что мешает аналитику создать метаданные под планируемые методы? Кодом не наполнять. И создать описания на эти пустышки.

Доступ к храну не имеют аналитики и это еще не этап разработки. Планируемое АПИ еще может быть не согласовано тем же тех.архитектором

**Comment by zerobig** [comment]
>Доступ к храну не имеют аналитики и это еще не этап разработки. Планируемое АПИ еще может быть не согласовано тем же тех.архитектором

Дык, это делать можно в любой базе. Даже в пустой.

**Comment by zerobig** [comment]
На этом считаю что на вопрос ответил.
