### ISSUE TITLE
В параметре запроса нет возможности указать максимальную, минимальную длину - аналог для объекта

### ISSUE THREAD

**Issue by Kyrales** [zerobig/swagger-1c#22]
Начал оформлять параметр запроса и столкнулся с невозможностью управлять длинной, аналогично как в объекте реализовано сейчас.
![image](https://github.com/user-attachments/assets/6947cbd2-2b68-4e8d-8dac-be2ebb83b41b)

**Comment by zerobig** [comment]
@Kyrales не нашел в спецификации [OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.yaml) такого. Можете ткнуть пальцем?

**Comment by zerobig** [comment]
Кстати, swagger-ui этот параметр игнорирует, а вот все остальные (redoc, rapidoc и stoplight) показывают. Любопытно.

**Comment by zerobig** [comment]
Возможно сделаю с пометкой в документации что в swagger-ui эти параметры не отображаются.

**Comment by zerobig** [comment]
9581fc1f6f149538d5ed9d75c753b6d417c66922 будет в релизе 1.2.6
