### ISSUE TITLE
Не создается рекурсивно структура описания объектов

### ISSUE THREAD

**Issue by dim-rudakov** [zerobig/swagger-1c#6]
Не создается рекурсивно структура описания объектов

Если в качестве описываемого типа данных идет тип object и у него в качестве свойств имеется другой тип object, то нижестоящий по иерархии тип object не разворачивается в swagger-описании свойств объекта рекурсивно

**Comment by zerobig** [comment]
![ca7f3a74-e7d5-49f0-b5d8-252ddf47d46e](https://github.com/user-attachments/assets/3ea4a0a0-a744-470f-aaf3-ce9898203b34)

**Comment by zerobig** [comment]
Не подтвердилась проблема.

![swagger-nested](https://github.com/user-attachments/assets/23edc388-78e7-473e-a200-efebf60b3b00)

Вроде бы всё получилось. Код должен быть примерно такой:

```bsl
Функция ПолучитьОбъектыHTTPСервиса() Экспорт

	TestObjectМассивСвойств = Новый Массив;
	TestObjectМассивСвойств.Добавить(Swag_ФормированиеОписаний.ОписаниеСвойстваОбъекта("name", , "string", , , , "Лист дерева"));
	TestObjectМассивСвойств.Добавить(Swag_ФормированиеОписаний.ОписаниеСвойстваОбъекта("children", , "array", , , "TestObject2"));
	
	Объекты = Новый Массив;
	Объекты.Добавить(Swag_ФормированиеОписаний.ОписаниеОбъекта(
		"TestObject2", "object", TestObjectМассивСвойств));
	
	Возврат Объекты;

КонецФункции
```

**Comment by zerobig** [comment]
Не подтвердилось. Закрыл.
Если будут ещё проблемы по этой задаче, то можно оставлять комментарии здесь же.
