### ISSUE TITLE
Дублирование свойств при использовании функционального стиля

### ISSUE THREAD

**Issue by johnnyshut** [zerobig/swagger-1c#8]
При добавлении свойств нового объекта, ему присваиваются все предыдущие свойства

```bsl
МассивСвойств = Новый Массив;
Если СтруктураОписания.Свойство("МассивСвойств") И ТипЗнч(СтруктураОписания.МассивСвойств) = Тип("Массив") Тогда
	МассивСвойств = СтруктураОписания.МассивСвойств;
КонецЕсли;
```
Соответственно лишние свойства или при совпадении имен получаем ошибку `duplicated mapping key`

Пример заполнения свойств и ошибка
![image](https://github.com/user-attachments/assets/346269e2-9199-451a-8f34-6f8e6a4edc2e)
![image](https://github.com/user-attachments/assets/876ac089-4471-44e3-8f6f-d0c78a08b259)

Если убрать дубли, то 
![image](https://github.com/user-attachments/assets/c6eedd6e-6abd-48d4-aab2-7b014f194da7)

**Comment by zerobig** [comment]
Спасибо за ваше замечание!
Я подозревал что что-то упустил при создании нового объекта, но забыл проверить именно такой момент.
День-два и выкачу патч. Если вы хотите поучаствовать в разработке, то добро пожаловать с pull request'ом.

**Comment by johnnyshut** [comment]
https://github.com/zerobig/swagger-1c/pull/9

**Comment by johnnyshut** [comment]
@zerobig посмотри, пожалуйста.
Внес больше исправлений, но все по мелочи.

**Comment by zerobig** [comment]
Круто! Спасибо!
